# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-11 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=200)),
                ('endservidor', models.CharField(max_length=200)),
                ('gadmin', models.CharField(max_length=200)),
                ('ou', models.CharField(max_length=200)),
                ('filter', models.TextField(verbose_name='Filtro')),
            ],
        ),
        migrations.CreateModel(
            name='obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=11, unique=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='sugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(default='uploads/default.png', upload_to='uploads/', verbose_name='Imagem')),
                ('datahora', models.DateTimeField(verbose_name='Data')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='obs',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sugestao'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
        ),
    ]
