# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-11-09 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=200)),
                ('endservidor', models.CharField(max_length=200)),
                ('gadmin', models.CharField(max_length=200)),
                ('ou', models.CharField(max_length=200)),
                ('filter', models.TextField(verbose_name='Filtro')),
                ('email_host', models.CharField(max_length=20)),
                ('email_port', models.CharField(max_length=10)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(max_length=50)),
                ('email_host_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Finalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=70)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
                ('imagem', models.ImageField(default='uploads/default.png', upload_to='uploads/', verbose_name='Imagem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', tinymce.models.HTMLField(max_length=10000)),
                ('imagem', models.ImageField(default='uploads/default.png', upload_to='uploads/', verbose_name='Imagem')),
                ('datahora', models.DateTimeField(verbose_name='Data')),
                ('senha', models.CharField(default='*', max_length=8)),
                ('status', models.BooleanField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='sugestao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='core.Sugestao'),
        ),
        migrations.AddField(
            model_name='obs',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sugestao'),
        ),
        migrations.AddField(
            model_name='finalizacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AddField(
            model_name='finalizacao',
            name='sugestao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Sugestao'),
        ),
        migrations.AddField(
            model_name='edicao',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sugestao'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
    ]
