# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-12 12:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='descricao',
            field=tinymce.models.HTMLField(max_length=10000),
        ),
    ]
