# Generated by Django 2.0 on 2022-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redirecionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirecionamento',
            name='depara',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
