# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-03 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sugestao_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='edicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.RenameField(
            model_name='obs',
            old_name='setor',
            new_name='sugestao',
        ),
        migrations.AddField(
            model_name='sugestao',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sugestao'),
        ),
        migrations.AddField(
            model_name='edicao',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sugestao'),
        ),
    ]
