# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-17 14:45
from __future__ import unicode_literals

from django.db import migrations

from Sugestao.core.models import Pessoa


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_redirecionamento_depara'),
    ]

    def insertData(apps, schema_editor):
        #Pessoaessoa = apps.get_model('pessoa')
        pessoa = Pessoa(nome="Anônimo", usuario="000000", status=True, email="Não informado")
        pessoa.save()

    operations = [
        migrations.RunPython(insertData),
    ]