# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200303_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='imagem',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/', verbose_name='Imagem'),
        ),
    ]
