# Generated by Django 2.0 on 2023-02-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cria_usuario_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='usuario',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
