# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resposta_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('datahora', models.DateTimeField(verbose_name='Data')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
                ('sugestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sugestao')),
            ],
        ),
    ]
