# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-07 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200617_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestao',
            name='senha',
            field=models.CharField(default='', max_length=8),
        ),
    ]
