# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-01 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200707_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='email_host',
            field=models.CharField(default='*', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='email_host_password',
            field=models.CharField(default='*', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='email_host_user',
            field=models.CharField(default='*', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='email_port',
            field=models.CharField(default='*', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
