# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-11-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211109_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sugestao'),
        ),
        migrations.AlterField(
            model_name='finalizacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AlterField(
            model_name='finalizacao',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idsugestao', to='core.Sugestao'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sugestao'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='core.Sugestao', unique=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
    ]
